"""init

Revision ID: c6102cf60f29
Revises: 
Create Date: 2026-04-06 22:41:47.923047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6102cf60f29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('google_places_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafes_google_places_id'), 'cafes', ['google_places_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('home_cafe_id', sa.UUID(), nullable=True),
    sa.Column('default_review_visibility', sa.String(length=10), nullable=False),
    sa.Column('characteristic_ordering', postgresql.ARRAY(sa.INTEGER()), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('notify_new_follower', sa.Boolean(), nullable=False),
    sa.Column('notify_followed_rating', sa.Boolean(), nullable=False),
    sa.Column('notify_monthly_recap', sa.Boolean(), nullable=False),
    sa.Column('notify_inactivity', sa.Boolean(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_table('monthly_tier_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_tier_list_user_month')
    )
    op.create_index(op.f('ix_monthly_tier_lists_user_id'), 'monthly_tier_lists', ['user_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('thumb', sa.String(length=4), nullable=True),
    sa.Column('coffee_quality', sa.SmallInteger(), nullable=False),
    sa.Column('food', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=False),
    sa.Column('noise', sa.SmallInteger(), nullable=False),
    sa.Column('crowd', sa.SmallInteger(), nullable=False),
    sa.Column('aesthetic', sa.SmallInteger(), nullable=False),
    sa.Column('comfort', sa.SmallInteger(), nullable=False),
    sa.Column('wifi', sa.SmallInteger(), nullable=False),
    sa.Column('privacy', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('last_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cafe_id', name='uq_visit_user_cafe')
    )
    op.create_index(op.f('ix_visits_cafe_id'), 'visits', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_visits_user_id'), 'visits', ['user_id'], unique=False)
    op.create_table('tier_list_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier_list_id', sa.UUID(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_list_id'], ['monthly_tier_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier_list_entries_tier_list_id'), 'tier_list_entries', ['tier_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tier_list_entries_tier_list_id'), table_name='tier_list_entries')
    op.drop_table('tier_list_entries')
    op.drop_index(op.f('ix_visits_user_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_cafe_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_monthly_tier_lists_user_id'), table_name='monthly_tier_lists')
    op.drop_table('monthly_tier_lists')
    op.drop_table('follows')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cafes_google_places_id'), table_name='cafes')
    op.drop_table('cafes')
    # ### end Alembic commands ###
